### ISSUE TITLE
ValueError: CEP must be a non-empty string containing only numbers

### ISSUE THREAD

**Issue by LinoLuiz** [mstuttgart/pycep-correios#77]
Estou tentando obter endereços (Logradouros) a partir de uma lista de CEPs de uma base de dados. Porém está ocorrendo o erro descrito no título, mesmo a coluna em questão sendo do tipo integer e não contém valores nulos.

```
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pycep_correios
import pandas as pd
import psycopg2

conexao = psycopg2.connect(host='meuhost', database='table', user='user', password='password')
cursor = conexao.cursor()
cursor.execute('SELECT cep FROM tb_loja')
result = cursor.fetchall()
df = pd.DataFrame(result)
df.columns = [columns[0] for columns in cursor.description]

def get_adress(cep):
    end = pycep_correios.get_address_from_cep(cep)
    return end['logradouro']

geolocator = Nominatim(user_agent='cep_lat_long')
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
df['address'] = df['cep'].apply(get_adress)
print(df)
```

ERRO:

```
Traceback (most recent call last):
  File "C:/Users/linol/Documents/parquet/cep_test.py", line 21, in <module>
    df['address'] = df['cep'].apply(get_adress)
  File "C:\Users\linol\Documents\parquet\venv\lib\site-packages\pandas\core\series.py", line 4213, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "C:/Users/linol/Documents/parquet/cep_test.py", line 15, in get_adress
    end = pycep_correios.get_address_from_cep(cep)
  File "C:\Users\linol\Documents\parquet\venv\lib\site-packages\pycep_correios\client.py", line 31, in get_address_from_cep
    cep = _format_cep(cep)
  File "C:\Users\linol\Documents\parquet\venv\lib\site-packages\pycep_correios\client.py", line 54, in _format_cep
    raise ValueError('CEP must be a non-empty string containing only numbers')  # noqa
ValueError: CEP must be a non-empty string containing only numbers

Process finished with exit code 1
```

**Comment by mstuttgart** [comment]
@LinoLuiz olá, tudo bem? Primeiramente obrigado por usar a Pycep-Correios. 😁 

Pela mensagem de erro 

> ValueError: CEP must be a non-empty string containing only numbers

e pelo que você descreveu, você deve estar fornecendo valores do tipo 'integer' para a pycep-correios. Porém ela trabalha apenas com valores strings.

O que eu faria nesse caso seria a conversão do tipo do dado que você pegou pelo banco:

```python
def get_adress(cep):
    cep_str = str(cep)
    end = pycep_correios.get_address_from_cep(cep_str)
    return end['logradouro']
```

Isso deve resolver o erro! Se deixei passar algum detalhe, por favor me avise.

Só uma observação que eu gostaria de fazer é realizar a busca de cep em lote (várias buscas de uma vez). Os servidores que a PyCEP Correios utilizam não recomendam muito bem esse tipo de operação. Então seria interessante se atentar com a quantidade de CEPs buscados em sequência. blz?

Qualquer dúvida só falar!

**Comment by LinoLuiz** [comment]
Opa, era isso mesmo. Eu estava tentando converter para str mas da maneira incorreta. Obrigado pelo apoio e dica.
Obs.: Existe alguma margem de quantidade de cep buscados, que começa a dar problema nestas buscas? Ex.: de 50 em 50 as buscas ocorrem normalmente.

**Comment by mstuttgart** [comment]
@LinoLuiz que bom que deu certo!

Então, sobre as margens de busca eu não tenho uma resposta precisa. Eu procurei me informar com o suporte de alguns dos respectivos servidores e me informaram que não havia margem, que limitar o número de buscas era mais por questões de não sobrecarregar o servidor (já que alguns dos serviços são gratuitos e não possuem um servidor robusto que aguente um número muito alto de requisições). Porém, eu já tive relatos de alguns usuários que a busca de CEP deles falharam ou ficaram alguns minutos 'fora do ar' quando fizeram uma busca em lote com muitos CEPs. Porém, eu acredito que de 50 em 50 não deve dar problema.
